### ISSUE TITLE
the purpose of using bert model and linear model

### ISSUE THREAD

**Issue by 24630** [RFCNLP/RFCNLP#12]
Hi！Annotated RFCs in the "rfcs-annotated" folder can be generated by annotating manually the original RFC document in the "rfcs-original" folder, then run tidy_documents.py to generate the tided version in "rfcs-annotated-tided" folder.The Gold FSM can be generated by running the XML file in "rfcs-annotated-tided" folder with nlp2promela. py . Since the FSM in the RFC document can be directly extracted through manual annotation, why do we need to train with the bert model and the linear model? What is the purpose of training with these two models?

**Comment by maxvonhippel** [comment]
Hi @24630 -- the purpose of these models is to do the manual process, automatically.  Annotating by hand is a huge pain.  What we show in our paper is you can get good results even if you annotate automatically.

**Comment by 24630** [comment]
But the inputs to these models are BIO-tags generated from XML files in the "rfcs-annotated-tidied" folder. The XML files in the "rfcs-predicted" folder generated by "linear.py" and "bert_bilstm_crf.py" seem to only extract the annotated parts of the XML files in the "rfcs-annotated-tidied" folder and delete the content without annotations. So it seems that these models did not automatically annotate the XML files in the "rfcs-annotated-tidied" folder, and the content of the XML files in the "rfcs-predicted" folder obtained by these two models is also the same.

**Comment by mlpacheco** [comment]
We train models to predict every tag that is inside `<control>` statements. This was a research project, and the problem is simplified as follows: given that we know what parts of the RFC are relevant to the FSM (the block of text inside `<control>` statements), can we identify the components that would allow us to automatically build an FSM. To do this, we come up with an annotation structure with the following tags:  -- `trigger`, `transition`, `action`, `error`, `variable`. Those are the tags that we learn to predict. 

If you follow the README, you can see that to generate the predicted files, you need to train models and then predict. 

In this repository, we have manual annotations for all protocols because we need them for evaluation purposes. Namely, we train on K-1 protocols, and predict/test on 1 protocol, and report results. Then, we run attack synthesis for TCP and DCCP only. 

For more details, please see: [issue 4](https://github.com/RFCNLP/RFCNLP/issues/4) and [issue 2](https://github.com/RFCNLP/RFCNLP/issues/2)

**Comment by 24630** [comment]
I see.Thank you so much for answering my questions!
