### ISSUE TITLE
Explanation of nested <control>

### ISSUE THREAD

**Issue by crearick** [RFCNLP/RFCNLP#4]
In the paper, you mention " We keep track of the indentation in the original documents to infer the scope of `<control>`."
However, if you look at this particular example from your GitHub repository, There are some nested `<control>`s in [lines 45 to 67](https://github.com/RFCNLP/RFCNLP/blob/main/rfcs-predicted-paper/bert_pretrained_rfcs_crf_phrases_feats/TCP.xml#L45).
However, in the original RFC, there are no indentations corresponding to [these inner `<contol>`s](https://github.com/RFCNLP/RFCNLP/blob/main/rfcs-original/TCP.txt#L2386).
Could you please explain how the scope of thse inner controls were identified?

**Comment by mlpacheco** [comment]
Hi @crearick. First of all, thank you for your interest and sorry for the confusion. 

In principle, we did not tackle the challenge of identifying the parts of the RFC that were relevant for the FSM, and focused instead on the inner components. In other words, we did not predict the `control` blocks, and instead focused on the other tags -- namely, `trigger`, `transition`, `action`, `error`, `variable`. For the `xml` files that you link, the control structure was tracked using the **orginal annotations**. If you take a look at https://github.com/RFCNLP/RFCNLP/blob/main/nlp-parser/preprocess_phrases.py, we keep track of the indentation/recursion on variables `level_horizontal` and `level_deep`, and those are the ones that are used in the `write_results` function in https://github.com/RFCNLP/RFCNLP/blob/main/nlp-parser/data_utils_NEW.py#L899 to write the XML files. I will make sure add a clarification about this and document the preprocessing process in the `README`. 

That being said, we did experiment with looking **_only_** at the structure of the **original non-annotated document**, by keeping track of indentation and sentence boundaries, instead of the annotated recursion. To show this, I have added the following scripts. All these changes are merged in [this commit](https://github.com/RFCNLP/RFCNLP/commit/afcd848a50951595504b44468d0d50589dc348c1) 

- `nlp-parser/track_format.py`: Tracks the indentation/sentence boundary and adds it to the annotation
- `preprocess_phrases_infer_struct.py`: Preprocessing script that reads the metadata tracked instead of keeping track of the recursion
- These generated the following files for TCP and DCCP:
     - Annotated files with indent and sentence count metadata: `rfcs-annotated-tidied/TCP-format.xml` and `rfcs-annotated-tidied/DCCP-format.xml`
     - Preprocessed files: `rfcs-bio/TCP_phrases_infer_struct.txt` and `rfcs-bio/DCCP_phrases_infer_struct.txt`
     - Added a`--struct_infer` flag on `nlp-parser/linear.py` to use the files generated by the scripts above. I have saved the output of this prediction to `rfcs-predicted-infer-struct/linear_phrases`. It can be added to the other prediction models in a similar manner.
- You can now run `nlp2promela.py` on these files, you will find that results are equivalent for TCP and pretty close for DCCP :)

I only did this for TCP and DCCP since these are our FSM test cases. The approach to scope out controls does not make any difference to the NLP pipeline or the training procedure, given that controls are not part of it, so I didn't bother to add it for the other protocols. 

Note that while this solves relying on annotations for the recursive controls, it still does not take care of identifying the **_outer_** controls. We are currently looking into some alternatives for this, including framing it as its own learning task. This will allow us to support more protocols out of the box, which has been brought up in issue https://github.com/RFCNLP/RFCNLP/issues/2. 

Stay tuned!
